[package]
name = "aoc-2025"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "secret-entrance"
path = "src/day-1/secret-entrance.rs"

[[bin]]
name = "gift-shop"
path = "src/day-2/gift-shop.rs"
